In [2]:
import numpy as np
import pandas as pd

In [ ]:
# creatig a single neuron
input = [1, 2, 3, 4]
weight = [0.2, 0.8, -0.5, 0.5]
bias = 2

In [13]:
# dot product the input and weight matrix
output = (input[0]*weight[0] + 
          input[1]*weight[1] + 
          input[2]*weight[2] + 
          input[3]*weight[3] + bias)


In [14]:
# apply the output to Relu activation function
a = max(0, output)
print(a)

4.3


In [ ]:
# Build 3 neuron having 3 by 3 matrix of weights

inputs = [1.3, 2.4, 3.6]

weights1 = [0.2, 0.8, -0.5]
weights2 = [0.5, -0.84, 0.53]
weights3 = [-0.21, -0.62, 0.16]

bias1 = 2
bias2 = 4
bias3 = 0.8

# Neuron 1
output = [ inputs[0] * weights1[0] + 
          inputs[1] * weights1[1] +
          inputs[2] * weights1[2] + bias1,
# Neuron 2
    inputs[0] * weights2[0] + 
    inputs[1] * weights2[1] +
    inputs[2] * weights2[2] + bias2,
# Neuron 3
    inputs[0] * weights3[0] + 
    inputs[1] * weights3[1] +
    inputs[2] * weights3[2] + bias3
]

print(output)


[2.38, 4.542, -0.385]


In [18]:
inputs = [1.3, 2.4, 3.6, -1.8]
weights = [[0.2, 0.8, -0.5, 0.3],[0.5, -0.84, 0.53, -0.3],[-0.21, -0.62, 0.16, 0.78]]
bias = [2, 4, 0.8]
layer_outputs = []
for neuron_weights, neuron_bias in zip(weights, bias):
    neuron_output = 0
    for n_input, weight in zip(inputs, neuron_weights):
        neuron_output += n_input * weight
    neuron_output += neuron_bias
    layer_outputs.append(neuron_output)
print(layer_outputs)



[1.8399999999999996, 5.082, -1.7890000000000004]


In [ ]:
# creating 4 neuron
inputs = [1.3, 2.4, 3.6, -1.8]

weights = [[0.2, 0.8, -0.5, 0.3],
           [0.5, -0.84, 0.53, -0.3],
           [-0.21, -0.62, 0.16, 0.78],
           [0.14, -0.45, 0.62, -0.19]]

bias = [2, 4, 0.8, -1.2]

# for loop to dot product weights and inputs

layer_outputs = []

for neuron_weights, neuron_bias in zip(weights, bias):
    neuron_output = 0
    for n_input, weight in zip(inputs, neuron_weights):
        neuron_output += n_input * weight
    neuron_output += neuron_bias
    layer_outputs.append(neuron_output)
    
print(layer_outputs)



[1.8399999999999996, 5.082, -1.7890000000000004, 0.4760000000000002]


In [ ]:
# creatig a single neuron
input = [1, 2, 3, 4]
weight = [0.2, 0.8, -0.5, 0.5]
bias = 2

# dot product the input and weight matrix with numpy
output = np.dot(input, weight) + bias
print(output)


4.3


In [ ]:
# creating a layer having 4 inputs
inputs = [
    [1.3, 2.4, 3.6, -1.8],
    [2.3, 4.5, -6.7, 1.2],
    [-2.3, 4.5, 6.7, -1.2],
    [1.2, 2.3, 4.5, 6.7]]
weights = [[0.2, 0.8, -0.5, 0.3],
           [0.5, -0.84, 0.53, -0.3],
           [-0.21, -0.62, 0.16, 0.78],
           [0.14, -0.45, 0.62, -0.19]] 
bias = [2, 4, 0.8, -1.2]

output = np.dot(inputs, np.array(weights).T) + bias 

print(output)

[[ 1.84   5.082 -1.789  0.476]
 [ 9.77  -2.541 -2.609 -7.285]
 [ 1.43   2.981 -1.371  0.835]
 [ 3.84   3.043  5.068 -0.55 ]]


In [ ]:
# creating 2 layers having 4 inputs

inputs = [1.3, 2.4, 3.6, -1.8]

weights1 = [[0.2, 0.8, -0.5, 0.3],
           [0.5, -0.84, 0.53, -0.3],
           [-0.21, -0.62, 0.16, 0.78],
           [0.14, -0.45, 0.62, -0.19]]
bias1 = [2, 4, 0.8, -1.2]


weights2 = [[0.2, 0.8, -0.5, 0.3],
           [0.5, -0.84, 0.53, -0.3],
           [-0.21, -0.62, 0.16, 0.78],
           [0.14, -0.45, 0.62, -0.19]]
bias2 = [2, 4, 0.8, -1.2]

output1 = np.dot(inputs, np.array(weights1).T) + bias1
# apply Relu activation function
output1 = np.maximum(0, output1)
print("Output for the first layer: ",*output1, sep=', ')

output2 = np.dot(output1, np.array(weights2).T) + bias2
# apply Relu activation function
output2 = np.maximum(0, output2)
print("Output for the second layer: ",*output2, sep=', ')






Output for the first layer: , 1.8399999999999999, 5.082000000000001, 0.0, 0.4760000000000002
Output for the second layer: , 6.576400000000001, 0.5083199999999994, 0.0, 0.0
